/* returns index or -1 if not found */
static int cache_free_uri(schema_cache *cache, const xmlChar *uri){
    int i;

    for (i = 0; i < cache->count; i++)
        if (xmlStrEqual(cache->uris[i], uri))
        {
            heap_free(cache->uris[i]);
            return i;
        }

    return -1;
}

// Generated by Amazon CodeWhisperer
static int cache_free_uri(schema_cache *cache, const xmlChar *uri) 
{
    int i;
    for (i = 0; i < cache->uri_count; i++) {
        if (cache->uri_list[i] == uri) {
            return i;
        }
    }
    return -1;
}