/**
 * Called by a macro, used on platforms where we can't determine the
 * calling function name.
 */
void
rs_log0_nofn(int level, char const *fmt, ...){
    va_list         va;

    va_start(va, fmt);
    rs_log_va(level, NULL, fmt, va);
    va_end(va);
}

//Generated by Amazon CodeWhisperer
void
rs_log0_nofn(int level, char const *fmt, ...) 
{
	va_list ap;

	va_start(ap, fmt);

	rs_log0_v(level, fmt, ap);

	va_end(ap);
}