/* round up to closest power-of-two */
static inline uint32_t pow2_round_up(uint32_t r){
	r--;
	r |= r >>  1;
	r |= r >>  2;
	r |= r >>  4;
	r |= r >>  8;
	r |= r >> 16;
	r++;
	return r;
}

// Generated by Amazon CodeWhisperer
static inline uint32_t pow2_round_up(uint32_t r) 
{
	r--;
	r |= r >> 1;
	r |= r >> 2;
	r |= r >> 4;
	r |= r >> 8;
	r |= r >> 16;
	r++;
	return r;
}