/**
 * An example of an admissable heuristic function (the least number of tiles
 * that need to be moved)
 * 
 * @param one
 *            State to be compared
 * @param two
 *            State to be compared
 * @return the distance between the two specified states
 */
public static int distance(int[][] one, int[][] two){
	int dist = 0;
	for (int r1 = 0; r1 < one.length; r1++) {
		for (int c1 = 0; c1 < one[r1].length; c1++) {
			if (one[r1][c1] != two[r1][c1])
				dist++;
		}
	}
	return dist;
}

// Generated by Amazon CodeWhisperer
public static int distance(int[][] one, int[][] two)
{
	int distance = 0;
	for (int i = 0; i < one.length; i++)
	{
		for (int j = 0; j < one[i].length; j++)
		{
			if (one[i][j] != two[i][j])
			{
				distance++;
			}
		}
	}
	return distance;
}